version: '3.2'

services:
  nysernet:
    build:
      context: nysernet/
    volumes:
      - "/home/tthoma17/work/openvpn1:/etc/openvpn/"
      - "/tmp/nets:/tmp/nets"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net:/dev/net"
    ports:
      - "1200:1194"
    environment:
      NS_LOG: "Bgp=all|prefix_all:BgpLog=all|prefix_all"
    networks:
      - sim

  su:
    build:
      context: su/
    volumes:
    volumes:
      - "/home/tthoma17/work/openvpn1:/etc/openvpn/"
      - "/tmp/nets:/tmp/nets"
    devices:
      - "/dev/net:/dev/net"
    cap_add:
      - NET_ADMIN
    ports:
      - "1201:1194"
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      NS_LOG: "Bgp=all|prefix_all:BgpLog=all|prefix_all"
    networks:
      - sim
    depends_on:
      - nysernet

  google:
    build:
      context: google/
    volumes:
      - "/home/tthoma17/work/openvpn1:/etc/openvpn/"
      - "/tmp/nets:/tmp/nets"
    devices:
      - "/dev/net:/dev/net"
    cap_add:
      - NET_ADMIN
    ports:
      - "1202:1194"
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      NS_LOG: "Bgp=all|prefix_all:BgpLog=all|prefix_all"
    networks:
      - sim
    depends_on:
      - nysernet

networks:
  sim:
    driver: bridge
